### ISSUE TITLE
Aufgabe 7.2

### ISSUE THREAD

**Issue by belkinot** [OttosBinaryKnights/GTI#34]
Das sieht eher nach dem Kellerautomaten für 7.3 aus.

Ich habe 2 zustände 
q0 mit folgenden auf sich selbst zeigenden Regeln a/epsilon/z und b/epsilon/epsilon
q0 auf q1 epsilon/epsilon/epsilon

q1 a/z/epsilon und b/z/epsilon

**Comment by cyberkeiler** [comment]
q1 ist noch nicht als finaler Zustand markiert!
![automat2](https://cloud.githubusercontent.com/assets/9371903/11533421/e2e56214-9909-11e5-83b9-7273c7495b80.jpg)
